version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - "api_network"
  api:
    build: ./api
    ports:
      - "5000"
    restart: "always"
    networks:
      - "api_network"
    deploy:
      replicas: 5
networks:
  api_network:
