version: '3'

services:
  nginx:
    build: ./gateway
    ports:
      - '5000:80'
    depends_on:
    - web1
    - web2
    - web3
  web1:
    build: ./application
    ports:
      - '4001:4000'
    environment:
      - SERVER=1
  web2:
    build: ./application
    ports:
      - '4002:4000'
    environment:
      - SERVER=2
  web3:
    build: ./application
    ports:
      - '4003:4000'
    environment:
      - SERVER=3
