version: "3"

services:
  nginx:
    build: ./server
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - "api_network"
  api:
    build: ./api
    ports:
      - "5000"
    restart: "always"
    networks:
      - "api_network"
    deploy:
      replicas: 5
networks:
  api_network:
